### ISSUE TITLE
Preparing pil2-stark-js to be ported to C++ prover

### ISSUE THREAD

**Issue by xavi-pinsach** [0xPolygonHermez/pil2-stark-js#2]

**Comment by xavi-pinsach** [comment]
# TODO List (add all tasks pending)
- [X] Generate a STARK from PIL2 with one subproof and one air
- [X] Make pil2 stark tests (simple+fibonacci) work in this repo
- [X] Integrate PIL verify as a "debug" flag
- [X] Integrate basic verifiers circom circuits in tests

**Comment by RogerTaule** [comment]
- [X] Adapting prover to be ported to C++
- [ ] Integrating new parser (basic version done, pending to add subproof values and upgrade expressions binary)
- [ ] Working on expressions and hints
